# This Workflow performs a full release of Che
name: Release - Orchestrate Overall Release Phases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be released. Should be in format 7.y.z'
        required: true
        default: ''
      phases:
        description: 'List of comma-separated phases to perform; default should be "1,2,3,4,5,6,7"; omit phases that have successfully run'
        required: true
        default: '1,2,3,4,5,6,7'
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Login to docker.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Set up environment
        run: |
          python -m pip install --upgrade pip
          pip install yq
          python --version
          pip --version
          yq --version

          # install more repos
          sudo add-apt-repository -y ppa:openjdk-r/ppa || true # for jdk11
          sudo apt-get update -y || true
          # install more dependencies
          sudo apt-get -y -q install wget curl bash git 
          java -version

          # want git >=2.24, hub >=2
          hub --version # hub reports git version too

          # want >=5
          bash --version

          wget "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz"
          sudo tar -xzvf openjdk-11.0.2_linux-x64_bin.tar.gz
          sudo mv jdk-11.0.2 /usr/lib/jvm/
          export JAVA_HOME="/usr/lib/jvm/jdk-11.0.2"
          export PATH="$JAVA_HOME/bin:$PATH"

          java -version
          which java
          javac -version
          which javac

          # do we need any of these?
          # docker-ce          x86_64  3:19.03.14-3.el7            docker-ce-stable   24 M
          # gcc-c++            x86_64  4.8.5-44.el7                base              7.2 M
          # nodejs             x86_64  2:10.23.0-1nodesource       nodesource         20 M
          # yarn               noarch  1.22.5-1                    yarn              1.2 M
      - name: Release
        run: |
          CHE_VERSION="${{ github.event.inputs.version }}"
          echo "CHE_VERSION=${CHE_VERSION}"
          sed -i VERSION -r -e "s#CHE_VERSION=.*#CHE_VERSION=${CHE_VERSION}#"
          PHASES="${{ github.event.inputs.phases }}"
          echo "PHASES=${PHASES}"
          sed -i VERSION -r -e "s#PHASES=.*#PHASES=${PHASES}#"

          export CHE_MAVEN_SETTINGS=${{ secrets.CHE_MAVEN_SETTINGS}}
          export CHE_OSS_SONATYPE_GPG_KEY=${{ secrets.CHE_OSS_SONATYPE_GPG_KEY}}
          export CHE_OSS_SONATYPE_PASSPHRASE=${{ secrets.CHE_OSS_SONATYPE_PASSPHRASE}}
          export CHE_GITHUB_SSH_KEY=${{ secrets.CHE_GITHUB_SSH_KEY}}
          export CHE_NPM_AUTH_TOKEN=${{ secrets.CHE_NPM_AUTH_TOKEN}}

          git config --global user.name "Mykhailo Kuznietsov"
          git config --global user.email "mkuznets@redhat.com"
          export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          export CHE_BOT_GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
          set -e
          # determine which OS we're using: rhel or ubuntu
          cat /etc/os-release || true
          ./cico_release.sh ubuntu
